version: '3'
services:
  app:
    container_name: backend_app
    build: .
    ports: 
      - 3000:3000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres 
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
